# Generated by Django 5.1.7 on 2025-03-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_siteconfiguration_alter_githubstats_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_info',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_secondary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_title',
            field=models.CharField(default='Full Stack Developer', max_length=120),
        ),
    ]
