# Generated by Django 5.1.7 on 2025-03-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_siteconfiguration_hero_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='site_title',
            new_name='hero_title',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='owner_name',
            field=models.CharField(default='The Developer', max_length=30),
        ),
    ]
