# Generated by Django 5.1.7 on 2025-03-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_site_title_siteconfiguration_hero_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='app.siteconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='app.siteconfiguration')),
            ],
        ),
    ]
